DXE 2231 Add M1 support to cli-dns
akamai/cli-dns pull request #13
Opened 2023-04-25 10:56 UTC by mimazaka

2023-04-25 11:02 UTC, mgwoj requested changes

2023-04-25 13:48 UTC, Slonimskaia requested changes

2023-04-25 13:48 UTC, Slonimskaia commented on README.md
> +3. Move the binary (`akamai-dns` or `akamai-dns.exe`) in to your `PATH`
```suggestion
```

2023-05-05 08:14 UTC, majakubiec approved these changes

2023-05-05 08:18 UTC, wzagrajcz approved these changes

2023-05-05 08:19 UTC, Slonimskaia commented on CHANGELOG.md
> +## Version 0.5.0 (XXX YY, 2023)
please update date here

2023-05-05 08:24 UTC, Slonimskaia approved these changes

2023-05-05 08:30 UTC, mimazaka commented on README.md
> +1. Move the binary (`akamai-dns` or `akamai-dns.exe`) in to your `PATH`
To align with gtm we get rid of this line

2023-05-05 09:16 UTC, merged